# Generated by Django 5.1.15 on 2026-03-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
