# Generated by Django 5.1.15 on 2026-03-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='comments',
            field=models.TextField(blank=True, help_text='Markdown supported'),
        ),
    ]
