# Generated by Django 5.1.15 on 2026-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='venue_category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bar', 'Bar'), ('pub', 'Pub'), ('sandwich_place', 'Sandwich place'), ('bakery', 'Bakery'), ('food_truck', 'Food truck'), ('other', 'Other')], default='restaurant', max_length=20),
        ),
    ]
