# Generated by Django 5.1.15 on 2026-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_venue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closed',
            field=models.BooleanField(default=False, help_text='Restaurant has permanently closed'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide from the public list'),
        ),
    ]
