# Generated by Django 5.1.15 on 2026-04-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_add_hidden_and_closed'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE restaurants_restaurant SET michelin_status = 'selected' WHERE michelin_status = 'listed'",
            reverse_sql="UPDATE restaurants_restaurant SET michelin_status = 'listed' WHERE michelin_status = 'selected'",
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='michelin_status',
            field=models.CharField(choices=[('none', 'None'), ('selected', 'Selected'), ('bib_gourmand', 'Bib Gourmand'), ('one_star', '1 Star'), ('two_stars', '2 Stars'), ('three_stars', '3 Stars')], default='none', max_length=20),
        ),
    ]
