# Generated by Django 5.1.15 on 2026-04-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_tag_restaurant_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('is-info', 'Blue'), ('is-success', 'Green'), ('is-warning', 'Yellow'), ('is-danger', 'Red'), ('is-link', 'Purple'), ('is-primary', 'Teal'), ('is-dark', 'Dark')], default='is-info', max_length=20),
        ),
    ]
