# Generated by Django 5.1.15 on 2026-05-01 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_city_bbox_max_lat_city_bbox_max_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Internal rating 1-10. Leave blank for wishlist (not visited yet).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
