# Generated by Django 5.1.15 on 2026-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Used as the landing city and pre-filled in the admin add form.'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_city'),
        ),
    ]
