# Generated by Django 5.1.15 on 2026-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_seed_default_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide from the public site'),
        ),
    ]
