# Generated by Django 5.1.15 on 2026-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_city_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin to top of the list'),
        ),
    ]
